server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api1
  devtools:
    livereload.enabled: true
    restart.enabled: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3309/redis
    hikari:
      username: root
      password: 1234
      connectionTimeout: 10000
      maximum-pool-size: 15
      max-lifetime: 600000
      readOnly: false
      connection-test-query: SELECT 1

#jasypt:
#  encryptor:
#    # JasyptConfig에 정의한 빈 이름
#    bean: jasyptStringEncryptor
#    property:
#      prefix: ENC(
#      suffix: )